import { useState } from 'react';
import PageShell from '../../components/PageShell';
import Card, { Pill } from '../../components/Card';

function analyze(text){ const t=text.toLowerCase(); if(t.includes('chest')) return {urg:'Urgent', see:'Emergency care now', items:[['Possible cardiac issue','High','82%'],['Acid reflux or muscle strain','Moderate','48%']], care:['Call emergency services if chest pain is severe.','Sit upright and stay calm.'], red:['Sweating, breathlessness, fainting','Pain spreading to arm or jaw']}; if(t.includes('head')) return {urg:'Routine', see:'Pediatrician or Primary Care Physician', items:[['Tension-type headache','High','78%'],['Dehydration or fatigue','High','65%'],['Migraine','Moderate','52%']], care:['Ensure hydration with water.','Rest in a quiet, dark room.','Maintain consistent sleep schedule.','Limit screen time and eye strain.'], red:['Sudden thunderclap pain','Stiff neck with fever','Confusion or weakness','Vision loss or double vision']}; return {urg:'Routine', see:'Primary Care Physician', items:[['Common viral illness','Moderate','61%'],['Fatigue or dehydration','Moderate','55%']], care:['Hydrate and rest.','Track temperature and symptoms.','Seek care if symptoms worsen.'], red:['Breathing difficulty','Persistent high fever','Severe pain']}; }
export default function Analysis(){ const [sym,setSym]=useState(''); const [age,setAge]=useState('32'); const [dur,setDur]=useState('2 days, since morning'); const [res,setRes]=useState(null);
 return <PageShell title="Symptom Analyzer" subtitle="Describe what you're feeling. Our AI offers calm, structured triage — not a diagnosis.">
  <Card><label>What's bothering you?<textarea value={sym} onChange={e=>setSym(e.target.value)} placeholder="e.g. Sharp headache on left side for 2 days, mild nausea, sensitive to light"/></label><div className="form-grid two"><label>Age (optional)<input value={age} onChange={e=>setAge(e.target.value)}/></label><label>Duration (optional)<input value={dur} onChange={e=>setDur(e.target.value)}/></label></div><button className="primary" onClick={()=>setRes(analyze(sym||'headache'))}>♨ Analyze symptoms</button></Card>
  {res&&<Card><div className="badges"><Pill tone="mint">Urgency: {res.urg}</Pill><Pill tone="blue">See: {res.see}</Pill></div><h3>Possible conditions</h3>{res.items.map(x=><div className="condition" key={x[0]}><div><b>{x[0]}</b><p>Estimated match based on the provided symptoms.</p></div><Pill tone={x[1]==='High'?'blue':'mint'}>{x[1]} · {x[2]}</Pill></div>)}<h3>Self-care</h3><ul>{res.care.map(i=><li key={i}>{i}</li>)}</ul><h3 className="red">Red flags — seek care now</h3><ul>{res.red.map(i=><li key={i}>{i}</li>)}</ul><small>This is not a medical diagnosis. Please consult a healthcare professional for evaluation.</small></Card>}
 </PageShell> }
